<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><UseWPF>true</UseWPF><ApplicationManifest>app.manifest</ApplicationManifest><Version>0.1.0-alpha.1</Version><Product>SafeFileSync</Product><PublishSingleFile>true</PublishSingleFile><IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract><RuntimeIdentifier>win-x64</RuntimeIdentifier><SelfContained>true</SelfContained></PropertyGroup><ItemGroup><ProjectReference Include="../SafeFileSync.Infrastructure.Windows/SafeFileSync.Infrastructure.Windows.csproj"/></ItemGroup></Project>
