<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><UseWPF>true</UseWPF><ApplicationManifest>app.manifest</ApplicationManifest><Version>0.1.0-alpha.1</Version><Product>SafeFileSync</Product></PropertyGroup><ItemGroup><ProjectReference Include="../SafeFileSync.Infrastructure.Windows/SafeFileSync.Infrastructure.Windows.csproj"/></ItemGroup></Project>
